(function() {
var worker = window;
var starter = worker.setInterval(function() { initPhrases(); }, 100);
function initPhrases() {
if (!worker.GUIp_browser || !worker.GUIp.common) { return; }
worker.clearInterval(starter);

worker.GUIp_words = function() {
	return {
	// Этот параметр показывает текущую версию файла
	// Меняется только при _структурных_ изменениях.
	// Например: добавление, удаление, переименование секций.
	// Добавление фраз — НЕ структурное изменение
	version: 20,

	// Фразы
	phrases: {
		// Ключевые корни: лечис, зелёнка
		heal: [
			"Do something about your wounds!", "Heal yourself, my hero!", "Drink potions, restore your health!", "You look like you need a drink!", "Take a moment to rest!",
			"Try to stay alive! Heal your wounds quickly!", "Some rest would do you good!", "Don't deny that you love drinking! Do it!"
		],

		heal_field: [
			"Heal yourself, my hero.", "You look like you need a drink.", "Take a moment to rest!",
			"Try to stay alive!", "Take a break and eat something!", "Some rest would do you good.", "Don't deny that you love drinking."
		],

		// Ключевые корни: молись,
		pray: [
			"Pray to me, mortal!", "Praise me, for I am your god!", "Help me to help you and pray!", "Kneel in prayer!"
		],

		pray_field: [
			"Pray to me, mortal!", "I demand worship!", "Praise me, for I am your god!", "I will show you the light.", "How long ago have you been in a temple?",
			"I'm watching you.", "Praise me daily and nightly!", "Help me to help you and pray.", "Kneel in prayer!"
		],

		// Ключевые корни: жертва
		sacrifice: [
			"Sacrifice something!", "I demand a sacrifice!"
		],

		// Ключевые корни: опыт
		exp: [
			"Do you ever learn?", "Learn something!", "You need to learn about levelling up!"
		],

		// Ключевые корни: золото клад
		dig: [
			"Dig a hole!", "Look for some treasure!", "Dig up something of value!", "I hear there is treasure underground!",
			"Search for gold!", "There is plenty of gold underground.", "Dig right here, it's a good spot!", "Stop right there and dig.",
			"There is a treasure under that tree!", "Digging is the best exercise!"
		],

		// Работает: бей, ударь, ударов
		hit: [
    		"Hit the enemy harder!", "Smite your foe!", "Destroy your rival! Crush him!", "Use your special attack!", "Knock your rival out! Beat him!",
    		"Kick them where it hurts!", "Attack with all your might!", "Strike like a lightning!",
    		"Hit your enemy twice!", "Attack out of turn!"
		],

		hit_field: [
    		"Hit the monster harder!", "Smite your foe!", "Destroy your rival!", "Use your special attack!", "Knock your rival out!",
    		"Kick them where it hurts!", "Bring your wrath upon the opponent!", "Attack with all your might!", "Strike like a lightning!",
    		"Hit your enemy twice!"
		],

		// Ключевые корни: отби, щит
		// Ключевое слово: защищайся
		defend: [
			"Duck and cover!", "Use your shield!", "Try to block incoming damage!", "Defend yourself!", "Resistance is futile!",
			"Come back with your shield - or on it!", "Take cover!", "Duck and dodge!", "Roll over and duck!"
		],

		do_task: [
			"Complete your quest!", "Surely you can quest faster than that!", "Hurry up with your quest!"
		],

		cancel_task: [
			"Cancel your quest!", "This quest is pointless! Abandon it!", "I do not like this quest. Stop what you are doing at once!",
			"Drop what you’re holding, and cease questing!"
		],

		die: [
    		"Curl up and die!", "You die too often!", "I want you dead in the next five minutes!", "Play dead!"
		],

		town: [
    		"Go to town!", "Turn back!", "Return to town!", "Return to town with glory!"
		],

		// Ключевые корни: Север
		go_north: [
			"Go north!"
		],

		// Ключевые корни: Юг
		go_south: [
			"Go south!"
		],

		// Ключевые корни: Запад
		go_west: [
			"Go west!"
		],

		// Ключевые корни: Восток
		go_east: [
			"Go east!"
		],

		// Начало для фраз-вопросиков
		inspect_prefix: [
			"Examine", "Study", "Look at", "Disassemble"
		],

		// Ключевые слова для крафта
		craft_prefix: [
			"Combine", "Assemble"
		],

		// Префиксы во имя
		exclamation: [
			"For my pleasure", "For science", "Please", "For the Godville", "I command you", "Hey", "Quick",
			"I need you to do something for me", "Without hesitation"
		],
		
		mnemonics: [ ]
	},

	usable_items: {
		types: [
			'aura box',
			//'arena box',
			'black box',
			'boss box',
			//'coolstory box',
			'friend box',
			'gift box',
			'good box',
			'invite',
			'heal box',
			'charge box',
			'raidboss box',
			'smelter',
			'teleporter',
			'temper box',
			'to arena box',
			'transformer',
			'quest box',
			'treasure box'
		],
		descriptions: [
			'This item gives a new aura to the hero',
			//'Данный предмет можно активировать только во время дуэли',
			'This item can affect the hero in a good or bad way',
			'This item summons a boss-monster for the hero to fight',
			//'Этот предмет сочиняет о герое былину',
			'This item helps your hero find a new friend',
			'This spooky item can turn into something',
			'This item may give your hero a pleasant surprise',
			'Activating this item will increase the number of available invitations.',
			'This item can completely restore the hero\'s health',
			'This item adds one accumulator charge when activated',
			'This item makes the hero search for allies against an underground boss',
			'This item kills the monster or tries to melt a golden brick out of 3000 gold coins',
			'This item can teleport the hero into a random town',
			'This item makes hero\'s alignment more defined',
			'This item teleports the hero to the arena when activated',
			'This item can transform one or several bold items in inventory into golden bricks',
			'This item sends the hero on a mini-quest when activated',
			'There could be something valuable inside or some rubbish'
		]
	},

	pets: [
		{name: 'Ninja Tortoise', min_level: 18},
		{name: 'Ballpoint Penguin', min_level: 18},
		{name: 'Dust Bunny', min_level: 18},
		{name: 'Firefox', min_level: 18},
		{name: 'Rocky Raccoon', min_level: 18},
		{name: 'Santa Claws', min_level: 18, max_level: Infinity},
		{name: 'Satan Claus', min_level: 18, max_level: Infinity},
		{name: 'Significant Otter', min_level: 18},
		{name: 'Sun Dog', min_level: 18},
		{name: 'Talking Donkey', min_level: 18},
		{name: 'Prancing Pony', min_level: 24},
		{name: 'Vogon Poet', min_level: 24},
		{name: 'Stripeless Zebra', min_level: 24},
		{name: 'Biowolf', min_level: 30},
		{name: 'Bipolar Bear', min_level: 30},
		{name: 'Dandy Lion', min_level: 30},
		{name: 'Trojan Horse', min_level: 30},
		{name: 'Lightsaber-Toothed Tiger', min_level: 35},
		{name: 'Solar Bear', min_level: 40},
		{name: 'Heffalump', min_level: 40},
		{name: 'Were-panther', min_level: 40},
		{name: 'Double Dragon', min_level: 50},
		{name: 'Multi-legged Luggage', min_level: 50},
		{name: 'Alpha Centaur', min_level: 60},
		{name: 'Grounded Hog', min_level: 60},
		{name: 'Hyper Lynx', min_level: 65},
		{name: 'Philosoraptor', min_level: 70},
		{name: 'Dreaded Gazebo', min_level: 70},
		{name: 'Gummy Wyrm', min_level: 70},
		{name: 'Battlesheep', min_level: 76},
		{name: 'Vengeful Mole', min_level: 80},
		{name: 'Terror Bull', min_level: 82},
		{name: 'Godvilla', min_level: 90},
		{name: 'Inner Demon', min_level: 90},
		{name: 'Thesaurus Rex', min_level: 101}
	],

	special_monsters: [
		'Bricked','Enlightened','Glowing','Healing','Holiday',
		'Loaded','Questing','Shedding','Smith','Wealthy'
	],

	chosen_monsters: [
		'Holykeeper'
	],

	custom_craft: [
		{q:1,i:0,t:'box',d:'black boxes',l:'bcdmp',g:'bm'},
		{q:0,i:1,t:'chr',d:'charge boxes',l:'hps',g:'b'},
	],

	custom_informers: [
		{q:1,title:'field trader',type:0,expr:'gv.isTrading && !gv.inTown'},
		{q:1,title:'low supplies',type:0,expr:'gv.fightType == "sail" && gv.supplies <= 5'},
		{q:1,title:'fishing',type:0,expr:'gv.lastDiary ~* "pond smells fishy. Let|an unplanned fishing day|fishing rod behind... Let|Sat down to fish. Hooked|Hid under a huge cloud, so|true, the fish will bite for sure|Carp diem, right"'}
	],

	ally_blacklist: [
		{q:1,n:'Godname',r:'your optional commentary',s:'text-decoration:underline; color: red'},
		{q:1,n:'Othername',r:'the reasoning',s:''}
	],

	town_list: [
		{name: 'Godville', dst: ''},
		{name: 'Bumchester', dst: '10'},
		{name: 'Last Resort', dst: '20'},
		{name: 'Beerburgh', dst: '30'},
		{name: 'Trollbridge', dst: '50'},
		{name: 'Herowin', dst: '60'},
		{name: 'Los Demonos', dst: '70'},
		{name: 'Monsterdam', dst: '90'},
		{name: 'Tradeburg', dst: '100'},
		{name: 'Los Adminos', dst: '130'},
		{name: 'San Satanos', dst: '170'},
		{name: 'Godvillewood', dst: '210'},
		{name: 'Herolympus', dst: '250'},
		{name: 'Dogville', dst: '300'},
		{name: 'Anville', dst: '350'},
		{name: 'Deville', dst: '500'},
		{name: 'Lostway', dst: '660-750'},
		{name: 'Unspecifiedistan', dst: '800'}
	]

	};
};

worker.GUIp_locale = 'en';

worker.GUIp_i18n = {
	// superhero
	hero: ['hero', 'hero'],
	heroine: ['heroine', 'heroine'],
	ask1: 'Ask ',
	get inspect() { return ' to ' + ['examine', 'study', 'look at', 'disassemble'][Math.floor(Math.random()*4)] + ' '; },
	ask2: 'Ask ',
	get craft1() {
		return ' to ' + ['combine', 'assemble'][Math.floor(Math.random()*2)] + ' random combination of ';
	},
	get craft1a() {
		return ' to ' + ['combine', 'assemble'][Math.floor(Math.random()*2)] + ' "';
	},
	b_b: '<b>b</b>+<b>b</b>',
	b_b_hint: 'two bold',
	b_r: '<b>b</b>+r',
	b_r_hint: 'bold and regular',
	r_r: 'r+r',
	r_r_hint: 'two regular',
	craft2: ' items from the inventory.',
	craft2a: '" combination of items from the inventory.',
	get craft_verb() { return ['Combine', 'Assemble'][Math.floor(Math.random()*2)]; },
	close: 'close',
	help_dialog_capt: 'help dialog',
	how_to_update: 'How to update <b>Godville UI+</b> manually:',
	help_update_all: '<li>Check for a <a id="checkUIUpdate" title="Check for updates" href="#">new version</a> of the extension;</li>' +
		'<li>Install an update using directions in the <a href="'+GUIp.common.erinome_url+'/repo" title="Opens in a new tab" target="_blank">INSTALL file</a>.</li>',
	help_useful_links: 'Useful links: ' +
		'<a href="'+GUIp.common.erinome_url+'" title="Opens in a new tab" target="_blank">extension page</a>, ' +
		'<a href="/gods/Dungeoneer" title="Opens in a new tab" target="about:blank">dungeon phrases</a>, ' +
		'<a href="https://bitbucket.org/Erinome/erinome-godville-ui-plus/issues" title="Opens in a new tab" target="about:blank">issue tracker</a>.',
	help_ci_links: 'Custom informers: <a id="checkCIExpression" href="#" title="Check expression">check expression execution</a>.',
	help_reset_links: 'In case of errors: ' +
		'<a id="resetGVSettings" href="#" title="Reset Godville settings">reset Godville settings</a>, ' +
		'<a id="resetUISettings" href="#" title="Reset Erinome Godville UI+ settings">reset eGUI+ settings</a>.',
	reset_gv_settings: "Resetting Godville settings may fix some random errors with UI+, no user data will be lost. Continue?",
	reset_ui_settings: "Resetting UI+ settings may fix errors related to saving options, all UI+ settings will be lost! Continue?",
	ui_settings_top_menu: '<strong>ui+</strong>&nbsp;settings',
	getting_version_no: 'Getting the latest addon version number...',
	is_last_version: 'You have the latest version',
	is_last_version_desc: 'No further actions are required.',
	new_version_available: 'New version available!',
	is_not_last_version_1: 'Latest version — <b>',
	is_not_last_version_2: '</b>. Manual update is required.',
	proceed_to_next_step: ' Continue to the next step.',
	getting_version_failed: 'Checking new version failed',
	getting_version_failed_desc: 'Unable to determine the latest version number. Please try again later.',
	hero_health: 'Hero\'s health',
	inventory: 'Inventory',
	supplies: 'Supplies',
	gold: 'Gold',
	charges: 'Charges',
	allies_health: 'Allie\'s health' ,
	enemy_health: 'Enemy\'s health',
	exp: 'Experience (percents)',
	level: 'Level',
	health: 'Health',
	godpower: 'Godpower (percents)',
	task: 'Quest (percents)',
	monsters: 'Monsters',
	bricks: 'Bricks',
	logs: 'Logs',
	savings: 'Savings (thousands)',
	weapon: 'Weapon',
	shield: 'Shield',
	head: 'Head',
	body: 'Body',
	arms: 'Arms',
	legs: 'Legs',
	talisman: 'Talisman',
	death_count: 'Deaths',
	pet_level: 'Pet level',
	ark_creatures: 'God\'s creatures',
	trader_exp: 'Trader\'s experience (percents)',
	trader_level: 'Trader\'s level',
	unknown_item_type_title: 'Unknow trophy type in Godville UI+!',
	unknown_item_type_content: 'We have detected an unrecognized trophy type. Please report the following to the developer: ',
	godpower_label: 'Godpower',
	north: 'north',
	go_north: ' to go north',
	east: 'east',
	go_east: ' to go east',
	south: 'south',
	go_south: ' to go south',
	west: 'west',
	go_west: ' to go west',
	ask3: 'Ask ',
	defend: 'defend',
	ask4: 'Ask ',
	to_defend: ' to defend',
	pray: 'pray',
	ask5: 'Ask ',
	to_pray: ' to pray',
	heal: 'heal',
	ask6: 'Ask ',
	to_heal: ' to heal',
	hit: 'hit',
	ask7: 'Ask ',
	to_hit: ' to hit',
	sacrifice: 'sacrifice',
	ask8: 'Ask ',
	to_sacrifice: ' to sacrifice',
	mnemo_button: 'mnemonics',
	mnemo_title: 'lookup a voice from mnemonics dictionary',
	enemy_label: 'Enemy',
	boss_warning_hint: 'boss warning',
	boss_slay_hint: 'boss',
	small_prayer_hint: 'small prayer',
	small_healing_hint: 'small healing',
	unknown_trap_hint: 'trap blocked by pet',
	trophy_loss_trap_hint: 'trap: gold or trophy loss',
	low_damage_trap_hint: 'trap: low damage',
	moderate_damage_trap_hint: 'trap: moderate damage',
	move_loss_trap_hint: 'trap: move loss',
	boss_warning_and_trap_hint: 'boss warning and trap',
	boss_slay_and_trap_hint: 'boss and trap',
	treasury_hint: '<abbr title="Treasury might be located in this cell according to known hints">possible treasury</abbr>',
	treasury_th_hint: '<abbr title="Treasury might be located in this cell if an unknown wall exists between this cell and the hint">possible treasury</abbr> in Hotness Dungeon',
	health_label: 'Health',
	gold_label: 'Gold',
	inventory_label: 'Inventory',
	level_label: 'Level',
	task_label: 'Quest',
	death_label: 'Death Count',
	study: 'study',
	dig: 'dig',
	cancel_task: 'cancel',
	do_task: 'do',
	die: 'die',
	ask9: 'Ask ',
	to_study: ' to study',
	ask10: 'Ask ',
	to_dig: ' to dig',
	ask11: 'Ask ',
	to_cancel_task: ' to cancel current quest',
	ask12: 'Ask ',
	to_do_task: ' to do current quest quicker',
	ask13: 'Ask ',
	to_die: ' to die',
	milestones_label: 'Milestones Passed',
	return: 'return',
	ask14: 'Ask ',
	to_return: ' to go to the nearest town',
	monsters_label: 'Monsters Killed',
	bricks_label: 'Bricks for Temple',
	logs_label: 'Wood for Ark',
	savings_label: 'Savings',
	pet_status_label: 'Status',
	pet_level_label: 'Level',
	gte_unknown_penalty: 'Not enough data to determine the gold to experience conversion penalty. Will resolve after any conversion or in ',
	log_unknown_time: 'Not enough data to determine when the guaranteed log will be. Will resolve after receiving a log or in ',
	log_is_guaranteed: 'The log is guaranteed',
	log_isnt_guaranteed: 'The log isn\'t guaranteed',
	error_message_title: 'Godville UI+ error!',
	debug_mode_warning: 'Warning! Error details are shown because debug mode is enabled.',
	possible_actions: 'Possible actions:',
	if_first_time: 'If this error has occured for the first time — ',
	press_here_to_reload: 'press here to reload the page.',
	if_repeats: 'If this error repeats — ',
	press_here_to_show_details: 'press here to show the details of the error.',
	error_message_subtitle: 'Error description:',
	error_message_text: 'Text of the error:',
	error_message_stack_trace: 'Stack trace',
	error_message_in_old_version: 'Warning! Currently installed Godville&nbsp;UI+ version is outdated. Please try to update the extension as this error might be already fixed in the latest release.',
	and: ' and ',
	or: ' or ',
	ui_help: 'ui+&nbsp;help',
	// options
	import_success: 'You setting\'ve been imported successfully',
	import_fail: 'Incorrect settings string',
	ui_settings: 'UI+ Settings',
	import_prompt: 'Settings import:',
	export_prompt: 'Settings export:',
	bg_status_file: 'file',
	bg_status_link: 'link',
	bg_status_same: 'same',
	bg_status_error: 'error',
	// options-page
	profile_menu_settings: 'Settings',
	profile_menu_third_eye: 'Third Eye',
	profile_menu_informers: 'Informers',
	profile_menu_gadgets: 'Mobile Apps',
	profile_menu_invites: 'Invites',
	profile_menu_plogs: 'Recharges',
	ui_settings_capt: 'Godville UI+ settings',
	disable_voice_generators: 'Disable godvoice generators',
	voicegen_settings: 'Voice generators\' options',
	use_hero_name: 'Add hero name to the beginning of the voices',
	use_exclamations: 'Add exclamations to the voices',
	use_short_phrases: 'Make short voices consisting of only one phrase',
	disable_die_button: 'Disable "Die" button',
	relocate_craft_buttons: 'Show craft buttons on top of the inventory',
	fixed_craft_buttons: 'Don\'t hide craft buttons when combos available',
	enable_custom_craft: 'Enable <span id="span_ccraft" class="clickable">custom craft combos</a>',
	disable_logger: 'Disable logger',
	disable_logger_desc: 'Disable the ticker with colorful numbers',
	sum_allies_hp: 'Sum health in logger',
	sum_allies_hp_desc: 'while in battle, otherwise show values individually',
	relocate_duel_buttons: 'Move duel buttons',
	relocate_duel_buttons_desc: 'allows to move duel buttons into the pantheons section',
	relocate_duel_buttons_hint: 'which ones?',
	relocate_duel_buttons_arena: 'arena',
	relocate_duel_buttons_challenge: 'challenge',
	relocate_duel_buttons_dungeon: 'dungeon',
	relocate_duel_buttons_sail: 'sail',
	forbidden_title_notices: 'Choose notifications in window title',
	forbidden_title_notices_desc: 'allows to disable certain notifications in the title',
	forbidden_title_notices_hint: 'which ones?',
	forbidden_title_notices_pm: 'private message',
	forbidden_title_notices_gm: 'guild counsel',
	forbidden_title_notices_fi: 'new forum posts',
	use_background: 'Enable background',
	use_background_desc: 'Enable cloudy or another background',
	use_background_hint: 'which one?',
	use_background_cloud: 'cloudy',
	use_background_file: 'from file',
	use_background_link: 'from link',
	voice_timeout: 'Choose timeout length',
	voice_timeout_desc: 'instead of the default 20 seconds',
	voice_timeout_hint: 'input time (in seconds)',
	improve_discharge_button: 'Improve "Restore" button',
	improve_discharge_button_desc: 'use dynamic limit to require confirmation',
	hide_charge_button: 'Remove "Charge" button',
	hide_charge_button_desc: 'for those who don\'t buy charges',
	dungeon_settings: 'Dungeon Settings',
	relocate_map: 'Swap remote control with map',
	fast_wormholes: 'Fast but less reliable wormhole calculation',
	islands_map_settings: 'Islands Map Settings',
	islands_map_widen: 'expand sail map',
	islands_map_showcrd: 'show coordinates instead of distances',
	islands_map_rndcolors: 'randomize POI colors order',
	islands_map_dhh: 'do not highlight hints on hover',
	islands_map_mbc: 'show borders',
	islands_map_mfc: 'show all tiles',
	islands_map_conv: 'remember the map for sail broadcast page',
	islands_map_pdpm: 'always use maximum possible Rim distance',
	islands_map_shh: 'simplified hints highlighting',
	freeze_voice_button: 'Freeze godvoice button',
	freeze_voice_button_desc: 'freezes godvoice button in certain cases',
	freeze_voice_button_after_voice: 'after voice has been heard',
	freeze_voice_button_when_empty: 'when no voice text is entered',
	forbidden_craft: 'Choose crafting modes',
	forbidden_craft_desc: 'allows to globally disable crafting of certain types and categories of items',
	forbidden_craft_b_b: '<b>bold</b> + <b>bold</b>',
	forbidden_craft_b_r: '<b>bold</b> + regular',
	forbidden_craft_r_r: 'regular + regular',
	forbidden_craft_usable: 'including <b>activatable</b>',
	forbidden_craft_heal: 'including healing',
	disable_page_refresh: 'Disable automatic page refresh',
	disable_page_refresh_desc: 'when the hero page hangs (approved by the devs)',
	disable_laying_timer: 'Remove experience conversion timer',
	disable_laying_timer_desc: 'for those who are tired of it',
	informer_type_l: 'classic informer',
	informer_type_d: 'desktop informer',
	informer_type_s: 'sound informer',
	active_informers: 'Informer Settings',
	active_informers_desc: 'Notify about game events:',
	active_informers_usable_items: 'Notify about activatable trophies:',
	active_informers_full_godpower: 'full godpower',
	active_informers_much_gold: 'lots of gold',
	active_informers_dead: 'death',
	active_informers_low_health: 'low health (in fight or dungeon)',
	active_informers_fight: 'fight',
	active_informers_arena_available: 'arena available',
	active_informers_dungeon_available: 'dungeon available',
	active_informers_sail_available: 'sailing available',
	active_informers_selected_town: 'selected town nearby',
	active_informers_wanted_monster: 'wanted monster',
	active_informers_special_monster: '<span id="span_special" class="clickable">special</span> monster',
	active_informers_tamable_monster: '<span id="span_tamable" class="clickable">tamable</span> monster',
	active_informers_chosen_monster: '<span id="span_chosen" class="clickable">favourite</span> monster',
	active_informers_pet_knocked_out: 'pet knocked out',
	active_informers_close_to_boss: 'boss warning (dungeon)',
	active_informers_close_to_rival: 'rival warning (sailing)',
	active_informers_guild_quest: 'attempt to defect from the guild',
	active_informers_mini_quest: 'beginning of a mini-quest',
	active_informers_custom_informers: '<span id="span_informers" class="clickable">custom</span> informers',
	active_informers_check: 'check',
	active_informers_check_all: 'all',
	active_informers_or: 'or',
	active_informers_check_none: 'none',
	active_informers_arena_box: 'arena trophies',
	active_informers_aura_box: 'trophies giving an aura',
	active_informers_black_box: 'trophies randomly affecting a hero',
	active_informers_treasure_box: 'trophies containing a treasure',
	active_informers_boss_box: 'trophies summoning a boss monster',
	active_informers_charge_box: 'trophies giving a godpower charge',
	active_informers_coolstory_box: 'composing a tale',
	active_informers_gift_box: 'free golden brick',
	active_informers_friend_box: 'making random friend',
	active_informers_good_box: 'affecting a hero in a good way',
	active_informers_heal_box: 'restoring health',
	active_informers_invite: 'Godville invite',
	active_informers_raidboss_box: 'summoning an underground boss monster',
	active_informers_quest_box: 'sending hero into a mini-quest',
	active_informers_smelter: 'melting gold into a brick',
	active_informers_teleporter: 'teleporting into a town',
	active_informers_temper_box: 'changing hero\'s alignment',
	active_informers_to_arena_box: 'sending hero to arena',
	active_informers_transformer: 'transforming <b>items</b> into golden bricks',
	enable_desktop_alerts: 'Show desktop notifications',
	enable_informer_alerts: 'when informers are activated',
	enable_pm_alerts: 'when receiving new private messages',
	informer_custom_sound: 'Choose a sound for informers audio notification',
	informer_custom_sound_desc: 'instead of default battle mode "ding"',
	informer_custom_sound_arena: 'arena entering sound',
	informer_custom_sound_spar: 'spar request sound',
	informer_custom_sound_file: 'from file',
	informer_custom_sound_play: 'play current sound',
	informer_custom_sound_error_type: 'file type is unsupported, try mp3/wav/ogg',
	informer_custom_sound_error_size: 'file size is too large, try less than ',
	informer_alerts_timeout: 'Choose notifications timeout',
	informer_alerts_timeout_desc: 'instead of the default 5 seconds',
	informer_alerts_timeout_hint: 'input time (in seconds)',
	disable_links_autoreplace: 'Disable links autoreplace by images',
	disable_links_autoreplace_desc: 'in forum threads',
	disable_target_post_highlight: 'Do not mark target posts',
	disable_target_post_highlight_desc: 'in forum threads',
	custom_dungeon_chronicler: 'Choose Dungeon phrases base',
	custom_dungeon_chronicler_desc: 'instead of Dungeoneer',
	custom_dungeon_chronicler_hint: 'input name',
	disable_godville_clock: 'Disable Godville clock',
	disable_godville_clock_desc: 'on click at "Remote Control" header',
	localtime_godville_clock: 'Make clock use localtime',
	localtime_godville_clock_desc: 'instead of GMT+3 offset',
	theme_override: 'Remember selected color scheme',
	theme_override_desc: 'and override current on mismatch',
	show_godville_clock: 'Show Godville Clock',
	hide_godville_clock: 'Hide Godville Clock',
	warning_godville_clock: 'Using internal Godville time since connecting to external synchronization services is currently forbidden',
	enable_debug_mode: 'Enable debugging mode',
	enable_debug_mode_desc: 'just for developers',
	apply: 'Apply',
	options_saved: 'options saved at ',
	voices_capt: 'Voice phrases',
	voices_heal: 'Heal',
	voices_heal_field: 'Heal (field)',
	voices_pray: 'Pray',
	voices_pray_field: 'Pray (field)',
	voices_sacrifice: 'Sacrifice',
	voices_exp: 'Study',
	voices_dig: 'Dig',
	voices_hit: 'Hit',
	voices_hit_field: 'Hit (field)',
	voices_do_task: 'Do task',
	voices_cancel_task: 'Cancel task',
	voices_die: 'Die',
	voices_town: 'Return',
	voices_defend: 'Defend',
	voices_exclamation: 'Exclamation',
	voices_inspect_prefix: 'Inspect prefixes',
	voices_craft_prefix: 'Craft prefixes',
	voices_north: 'North',
	voices_south: 'South',
	voices_west: 'West',
	voices_east: 'East',
	voices_mnemonics: 'Mnemonics',
	voices_save: 'Save',
	voices_defaults: 'Reset to default',
	import_export_capt: 'Settings import/export',
	import_export_all: 'process all settings of all accounts',
	import_all_warning: 'You have requested the import of the whole Godville settings storage (not only eGUI+ settings!), this action can\'t be undone. Do you want to continue?',
	export_all_warning: 'You have requested the export of the whole Godville settings storage (not only eGUI+ settings!), do you want to continue?',
	import: 'Import',
	export: 'Export',
	settings_cloud_download: 'Download',
	settings_cloud_upload: 'Upload',
	settings_cloud_download_warning: 'You have requested the download of previously saved settings from the Cloud.\nPlease enter your keyword to continue:',
	settings_cloud_upload_warning: 'You have requested the upload of your settings to the Cloud.\nPlease create your own keyword to continue:',
	settings_cloud_wrong_keyword: 'Wrong keyword!',
	settings_cloud_error: 'Requested operation failed! Please try again later.',
	settings_cloud_missing: 'Your settings could not be found in the Cloud!',
	settings_cloud_download_ok: 'Your settings were successfully downloaded, please press "Import" to apply them.',
	settings_cloud_upload_ok: 'Your settings were successfully uploaded to the Cloud!',
	// forum
	Subscribe: 'Subscribe in UI+',
	Unsubscribe: 'Unsubscribe in UI+',
	subscribe: 'subscribe',
	unsubscribe: 'unsubscribe',
	subscribe_title: 'Notify about new messages in this topic via eGUI+',
	unsubscribe_title: 'Stop notifying about new messages in this topic via eGUI+',
	bold_hint: 'Bold',
	bold: 'B',
	underline_hint: 'Underline',
	underline: 'U',
	strike_hint: 'Strike',
	strike: 'S',
	italic_hint: 'Italic',
	italic: 'I',
	quote_hint: 'Quote',
	code_hint: 'Code',
	pre_hint: 'Pre',
	link_hint: 'Insert link',
	unordered_list_hint: 'Unordered list',
	ordered_list_hint: 'Ordered list',
	br_hint: 'Insert line breaker',
	sup_hint: 'Superscript',
	sub_hint: 'Subscript',
	monospace_hint: 'Monospace',
	monospace: 'ms',
	broadcast: 'broadcast',
	user_css: 'User CSS',
	open_chat_with: 'Open chat with god/goddess ',
	open_in_a_new_tab: 'Open in a new tab',
	north_east: 'north-east',
	north_west: 'north-west',
	south_east: 'south-east',
	south_west: 'south-west',
	burning: 'very hot (1-2 steps from treasure)',
	hot: 'hot (3-5 steps from treasure)',
	warm: 'warm (6-9 steps from treasure)',
	mild: 'mild (10-13 steps from treasure)',
	cold: 'cold (14-18 steps from treasure)',
	freezing: 'very cold (19 or more steps from treasure)',
	send_log_to_LEMs_script: 'Send the log to LEM\'s script',
	till_next_try: 'Till next try: ',
	tries_left: 'Tries left: ',
	till_next_try_s: 'avail in ',
	tries_left_s: 'tries: ',
	map: 'Map',
	map_cgm: 'map is generated from the campaign log',
	trace_map_start: 'Start trace',
	trace_map_pause: 'Pause trace',
	trace_map_stop: 'Stop trace',
	trace_map_next: 'Next step',
	trace_map_prev: 'Previous step',
	trace_map_progress_step: 'Selected step',
	trace_map_progress_stopped: 'Click to move progress',
	wrong_entries_order: 'The button works on another entries order only.',
	the_button_will_appear_after: 'The button will appear at ',
	step: '+ step.',
	get_your_map: 'Get your map',
	search_database: 'Search Database',
	relaxed_search: 'Relaxed search',
	exact: 'Exact',
	high_precision: 'High Precision',
	normal: 'Normal',
	primary: 'Primary',
	corrections: 'Corrections:',
	wormholes: 'Wormholes:',
	browser: 'Browser:',
	version: 'Version:',
	clear_voice_input: 'Clear voice input',
	trophy: 'trophy ',
	high_contrast: 'High contrast mode',
	save_log_to: 'Save to',
	map_pointer: 'Pointer',
	lb_add: 'Add row',
	lb_save: 'Save',
	lb_reset: 'Reset',
	lb_close: 'Close',
	lb_enable: 'Enable',
	lb_reset_confirm: 'Are you sure you want to reset this setting to its default value?',
	lb_pets_title: 'Customize tamable monsters',
	lb_pets_desc: 'List monsters that could be tamed:<br><i>name</i> <i>min_hero_level</i> [<i>max_hero_level</i>]',
	lb_chosen_monsters_title: 'Customize favourite monters',
	lb_chosen_monsters_desc: 'List monster names to notify when met:',
	lb_special_monsters_title: 'Customize special monters',
	lb_special_monsters_desc: 'List prefixes one by line:',
	lb_ally_blacklist_title: 'Setup your allies blacklist',
	lb_ally_blacklist_desc: 'List some allies to mark when met in battle modes:<br><i>godname</i> [<i>comment</i>] [<i>CSS</i>]',
	lb_custom_craft_title: 'Custom craft combination rules setup',
	lb_custom_craft_desc: 'List your craft combo rules:<br><i>title</i> <i>name</i> <i>starting_letters</i> <i>trophy types</i> (<a href="#" title="Parameters:\ntitle\t\t- short combo name (shown as button)\nname\t\t- full combo name (shown as hint)\nletters\t\t- first letters of trophies to merge\ntrophy groups\t- type of trophies to merge\n\nPossible types:\tb - bold, r - regular, m - mixed">?</a>)',
	lb_custom_informers_title: 'Custom informers setup',
	lb_custom_informers_desc: 'List your informer rules:<br><i>title</i> <i>logical_expression</i> <i>type</i> (<a href="#" title="Parameters:\ntitle\tvisible name\nexpression\tlogical expression (see FAQ for info)\ntype\t\t 0 = generic, 1 = user cancellable + (16 = label, 32 = desktop, 64 = sound)">?</a>) [<a href="' + GUIp.common.erinome_url + '/godville/?show=FAQ" target="_blank">FAQ</a>]',
	custom_informers_error: 'Error in expression',
	custom_informers_error_operator: 'Unsupported operator',
	custom_informers_error_identifier: 'Unsupported itentifier',
	custom_informers_error_expression: 'Unsupported expression type',
	custom_informers_error_duplicated: 'Using the same name for multiple informers is not allowed!',
	custom_informers_check: 'Custom informer expressions check',
	custom_informers_check_expr: 'Expression: ',
	custom_informers_check_result: 'Result: ',
	custom_informers_input: 'Please input expression you wish to test:',
	coords_error_title: 'Chronicle parsing failed!',
	coords_error_desc: 'Coordinates mismatch',
	step_n: 'Step #',
	confirm_item_activate: 'Proceed?',
	town_informer: 'Town informer',
	town_informer_curtown: 'Selected town',
	town_informer_choose: 'Select a town to inform about',
	town_informer_reset: 'Deselect the town',
	town_informer_gvroads: 'All the roads today lead to Godville',
	daily_forecast: 'Daily Forecast',
	daily_forecast_update_notice: 'Requested data update from Godville News!',
	forum_subs: 'Subscribed Topics',
	forum_subs_by: 'by',
	forum_subs_view: 'view',
	forum_subs_last: 'last',
	forum_subs_info: 'Last message by ',
	forum_subs_no_subs: 'You have no subscribed topics yet.',
	forum_subs_missing_subs: 'Subscribed topics not found!',
	forum_subs_limit_exceeded: 'You have exceeded the limit of available subscriptions!',
	forum_subs_rapid_exceeded: 'You have exceeded the limit of prioritized subscriptions!',
	forum_subs_count: 'Subscribed topics: ',
	forum_subs_rapid: ', prioritized: ',
	forum_subs_intv: ', updates every: ~',
	forum_replies: 'messages posted today',
	format_time_minute: 'min.',
	format_time_minutes: 'min.',
	format_time_hour: 'hour',
	format_time_hours: 'hours',
	format_time_ago: 'ago',
	sail_points: 'Marks',
	sail_points_desc: 'Show codes defining points of interest',
	sail_points_update: 'Update',
	sail_points_invalid: 'Invalid input!',
	sea_monster: 'Sea monster',
	sea_monster_report: 'Report this undetected sea monster to eGUI+ developer',
	saver_invalid_log: 'only godville chronicles are allowed for upload',
	saver_missing_log: 'the chronicle is missing',
	saver_missing_log_c: 'Sorry, but no duel chronicle could be found using this link',
	saver_broadcast_log: 'broadcasts are not allowed for upload',
	saver_broadcast_log_c: 'broadcast',
	saver_already_working: 'Chronicle is already being processed!',
	saver_error: 'An error occured when processing your chronicle. Please try again later.',
	badge_equip: 'Average equipment level',
	badge_skill: 'Skill training minimal cost',
	badge_pet1: 'Time to resurrect a pet',
	badge_pet2: 'Pet resurrection fee',
	ally_blacklist: 'Allies blacklist',
	ally_blacklist_desc: 'Mark allies from <span id="span_ally_blacklist" class="clickable">your blacklist</span> in battle modes',
	ally_blacklisted: 'Ally is on your list'
};

}
})();
